# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - DemoApp.UI

jobs:
- job: 'BuildUI'
  displayName: 'Build Demo UI'
  
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    buildConfiguration: 'Release'
    staticWebContentSAS: '$(Static Web Content SAS)'

  steps:
  - script: 'npm install'
    displayName: 'npm install'
    workingDirectory: 'DemoApp.UI'
  - script: 'npm run build -- --prod'
    displayName: 'npm build'
    workingDirectory: 'DemoApp.UI'
  - task: ArchiveFiles@2
    displayName: 'Archive build result'
    inputs:
      rootFolderOrFile: 'DemoApp.UI/dist/demo-app-ui'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactStagingDirectory)/DemoApp.UI.zip'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish build artifact'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'DemoApp.UI'
  - script: az storage blob upload-batch --destination \$web --source DemoApp.UI/dist/demo-app-ui --pattern \* --account-name stspaa56tu4bzkgjjw --sas-token $(staticWebContentSAS)
    displayName: 'Upload static web content'
