trigger:
  branches:
    include:
    - main
  paths:
    include:
    - '/DemoApp.Api/'

jobs:
- job: 'BuildAPI'
  displayName: 'Build Demo API'
  
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    buildConfiguration: 'Release'

  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET 5 SDK'
    inputs:
      version: '5.0.x'
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      workingDirectory: 'DemoApp.Api'
      command: 'build'
      arguments: '--configuration $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish'
    inputs:
      command: publish
      publishWebProjects: True
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: True
  - task: PublishBuildArtifacts@1
    displayName: 'Publish build artifact'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'DemoApp.API'
  - task: AzureWebApp@1
    displayName: 'Publish to Azure Web App'
    inputs:
      azureSubscription: 'Azure'
      appName: '$(WebAppName)'
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
      deploymentMethod: 'zipDeploy'
    